'use client';

import { useQuery } from '@tanstack/react-query';
import {
  Newspaper, Users, TrendingUp, MessageCircle,
  Bell, FileText, AlertTriangle, RefreshCw,
} from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Skeleton } from '@/components/ui/skeleton';
import StatCard from '@/components/dashboard/StatCard';
import ActivityChart from '@/components/dashboard/ActivityChart';
import RecentEvents from '@/components/dashboard/RecentEvents';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { analyticsApi, agentsApi } from '@/lib/api';
import { useAuthStore } from '@/store/authStore';
import { formatNumber } from '@/lib/utils';
import toast from 'react-hot-toast';
import { useState } from 'react';

export default function DashboardPage() {
  const { user } = useAuthStore();
  const [refreshing, setRefreshing] = useState(false);

  const { data: stats, isLoading, refetch } = useQuery({
    queryKey: ['dashboard-stats'],
    queryFn: () => analyticsApi.getDashboardStats(),
    select: (res) => res.data.data,
  });

  const { data: summary, isLoading: summaryLoading, refetch: refetchSummary } = useQuery({
    queryKey: ['daily-summary'],
    queryFn: () => agentsApi.getDailySummary(),
    select: (res) => res.data.data,
    staleTime: 60 * 60 * 1000, // 1 hour
  });

  const handleRefresh = async () => {
    setRefreshing(true);
    try {
      await Promise.all([refetch(), refetchSummary()]);
      toast.success('Dashboard refreshed');
    } finally {
      setRefreshing(false);
    }
  };

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold">Dashboard</h1>
          <p className="text-sm text-muted-foreground mt-0.5">
            Welcome back, {user?.name?.split(' ')[0]}. Here&apos;s what&apos;s happening.
          </p>
        </div>
        <Button variant="outline" size="sm" onClick={handleRefresh} disabled={refreshing}>
          <RefreshCw className={`w-4 h-4 mr-2 ${refreshing ? 'animate-spin' : ''}`} />
          Refresh
        </Button>
      </div>

      {/* Stats grid */}
      {isLoading ? (
        <div className="grid grid-cols-2 lg:grid-cols-4 gap-4">
          {Array.from({ length: 4 }).map((_, i) => (
            <Skeleton key={i} className="h-28 rounded-lg" />
          ))}
        </div>
      ) : (
        <div className="grid grid-cols-2 lg:grid-cols-4 gap-4">
          <StatCard
            title="News Articles"
            value={formatNumber(stats?.news?.total || 0)}
            change={`+${stats?.news?.new || 0} today`}
            changeType="positive"
            icon={Newspaper}
            iconColor="text-blue-400"
          />
          <StatCard
            title="Competitors"
            value={stats?.competitors?.total || 0}
            description="being tracked"
            icon={Users}
            iconColor="text-violet-400"
          />
          <StatCard
            title="Rising Trends"
            value={stats?.trends?.rising || 0}
            description="upward movement"
            icon={TrendingUp}
            iconColor="text-emerald-400"
          />
          <StatCard
            title="Avg Sentiment"
            value={`${((stats?.sentiment?.average || 0) * 100).toFixed(0)}%`}
            description="overall positive"
            icon={MessageCircle}
            iconColor="text-yellow-400"
          />
        </div>
      )}

      {/* Charts & Events */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        <div className="lg:col-span-2">
          <ActivityChart />
        </div>
        <RecentEvents events={stats?.recentEvents || []} />
      </div>

      {/* AI Executive Summary */}
      <Card>
        <CardHeader>
          <div className="flex items-center justify-between">
            <CardTitle className="flex items-center gap-2">
              <div className="w-2 h-2 rounded-full bg-primary animate-pulse-slow" />
              AI Executive Briefing
            </CardTitle>
            <div className="flex items-center gap-2 text-xs text-muted-foreground">
              <span>Generated by AI</span>
            </div>
          </div>
        </CardHeader>
        <CardContent>
          {summaryLoading ? (
            <div className="space-y-2">
              <Skeleton className="h-4 w-full" />
              <Skeleton className="h-4 w-5/6" />
              <Skeleton className="h-4 w-4/5" />
              <Skeleton className="h-4 w-full" />
              <Skeleton className="h-4 w-3/4" />
            </div>
          ) : summary?.finalInsight ? (
            <div className="ai-prose text-sm text-muted-foreground leading-relaxed">
              {summary.finalInsight}
            </div>
          ) : (
            <div className="flex flex-col items-center justify-center py-6 gap-3 text-center">
              <AlertTriangle className="w-8 h-8 text-muted-foreground" />
              <p className="text-sm text-muted-foreground">No AI summary available yet. Click refresh to generate one.</p>
            </div>
          )}
        </CardContent>
      </Card>

      {/* Quick stats row */}
      {!isLoading && (
        <div className="grid grid-cols-2 sm:grid-cols-4 gap-4">
          <StatCard
            title="Active Alerts"
            value={stats?.alerts?.active || 0}
            icon={Bell}
            iconColor="text-orange-400"
          />
          <StatCard
            title="Unread Notifications"
            value={stats?.notifications?.unread || 0}
            icon={AlertTriangle}
            iconColor="text-red-400"
          />
          <StatCard
            title="Recent Reports"
            value={stats?.reports?.length || 0}
            description="last generated"
            icon={FileText}
            iconColor="text-teal-400"
          />
          <StatCard
            title="Data Sources"
            value="6+"
            description="active collectors"
            icon={RefreshCw}
            iconColor="text-primary"
          />
        </div>
      )}
    </div>
  );
}
